name: deepCRE_CPU
channels:
- conda-forge

dependencies:
- python=3.9
- tensorflow=2.10.0

- pip
- pip:
  - git+https://github.com/AvantiShri/shap.git@29d2ffab405619340419fc848de6b53e2ef0f00c
  - altair==5.4.1
  - biopython==1.81
  - deeplift==0.6.13.0
  - numpy==1.26.4
  - pandas==2.2.3
  - streamlit==1.37.1
